# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161222_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/%Y/%m/%d'),
        ),
    ]
